version: "3.8"

# automatically build ffmpeg
# docker-compose up --build

# build
# docker-compose build

# run
# docker-compose run build-ffmpeg

# terminate and clean
# docker-compose down

services:
  build-ffmpeg:
    container_name: ubuntu-ffmpeg
    build: docker/
    # change below if your id not 1000
    user: 1000:1000
    working_dir: /usr/src/ffmpeg
    volumes:
      - ./ffmpeg-4.4.4:/usr/src/ffmpeg
      - ./build.sh:/usr/src/ffmpeg/build-script.sh
    environment:
      OUT_DIR: static-bins/
    command: ./build-script.sh


